org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false
minecraft_version=1.21.11
loader_version=0.18.4
loom_version=1.17.20
# Mod Properties
mod_id=ultramarine
mod_version=0.6.5-26.1-port
maven_group=org.voxelutopia.ultramarine.fabric
mod_name=Ultramarine
archives_base_name=ultramarine-rekindled
mod_credits=
mod_icon=logo.png
# Dependencies
# check this on https://modmuss50.me/fabric.html

#fabric_version=0.102.0+1.21
fabric_api_version=0.141.6+1.21.11

config_version=8.0.0

rei_version=21.11.816

moremcmeta_version=v1.21-4.5.0-fabric

#fabric_loom_version=1.9-SNAPSHOT
fabric_loom_version=1.17.20

jade_version=21.1.6+fabric

jei_version=27.38.0.97